services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: udemy_clone_api
    env_file:
      - .env
    volumes:
      - ./src:/app/src
    ports:
      - "8000:8000"
    command: uv run uvicorn app.main:app --app-dir src --host 0.0.0.0 --port 8000 --reload

  db:
    image: postgres:16-alpine
    container_name: udemy_clone_db
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
