"""create_user_table

Revision ID: 219fbf900bee
Revises:
Create Date: 2026-06-10 16:02:35.786528

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "219fbf900bee"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
