"""added subtitle columns to Lesson table

Revision ID: 2fac1fca84fc
Revises: b1a2c3d4e5f6
Create Date: 2026-08-03 18:48:41.437463

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2fac1fca84fc"
down_revision: str | Sequence[str] | None = "b1a2c3d4e5f6"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

subtitle_status_enum = postgresql.ENUM(
    "PENDING",
    "PROCESSING",
    "COMPLETED",
    "FAILED",
    name="subtitlestatustype",
)


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    subtitle_status_enum.create(op.get_bind(), checkfirst=True)
    op.add_column("lessons", sa.Column("transcript_path", sa.String(), nullable=True))
    op.add_column("lessons", sa.Column("subtitles_path", sa.String(), nullable=True))
    op.add_column(
        "lessons",
        sa.Column(
            "subtitle_status",
            subtitle_status_enum,
            nullable=False,
            server_default="PENDING",
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("lessons", "subtitle_status")
    op.drop_column("lessons", "subtitles_path")
    op.drop_column("lessons", "transcript_path")
    subtitle_status_enum.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
