"""creating Cart and CartItem tables

Revision ID: 6b1855bea1d5
Revises: afc42138d510
Create Date: 2026-07-08 17:23:24.564405

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "6b1855bea1d5"
down_revision: str | Sequence[str] | None = "afc42138d510"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
