"""add upload status columns to lesson table

Revision ID: 94b495286a6c
Revises: 2fac1fca84fc
Create Date: 2026-08-11 01:03:50.021478

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "94b495286a6c"
down_revision: str | Sequence[str] | None = "2fac1fca84fc"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

upload_status_enum = postgresql.ENUM(
    "QUEUED", "PROCESSING", "READY", "FAILED", name="uploadstatustype"
)


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    upload_status_enum.create(op.get_bind(), checkfirst=True)
    op.add_column(
        "lessons", sa.Column("upload_id", sa.String(length=32), nullable=True)
    )
    op.add_column(
        "lessons", sa.Column("upload_status", upload_status_enum, nullable=True)
    )
    op.add_column(
        "lessons",
        sa.Column("upload_failure_reason", sa.String(length=255), nullable=True),
    )
    op.create_index(op.f("ix_lessons_upload_id"), "lessons", ["upload_id"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_lessons_upload_id"), table_name="lessons")
    op.drop_column("lessons", "upload_failure_reason")
    op.drop_column("lessons", "upload_status")
    op.drop_column("lessons", "upload_id")
    upload_status_enum.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
